### ISSUE TITLE
datos incompletos en el gist de results.json

### ISSUE THREAD

**Issue by martinbel** [durancristhian/quiniela-results#7]
Buenas, 

Estaba mirando el [gist](https://gist.github.com/durancristhian/48260f353f75d51261b92ebb1cdf9bac)  y los datos estan incompletos, supongo por limites de gist. Creo que la fecha más actual es 2006-09. 

Saludos.

**Comment by durancristhian** [comment]
Hola @martinbel, perdón por tardar en responder, cosas de la vida 😅

Si, gist automáticamente truncó los resultados, pero el file estaba completo. Fijate que en otro repo que tengo llamado `quiniela-history` explico como generarlo por si te sirve :)
